# Generated by Django 2.2.10 on 2020-04-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('name', models.CharField(max_length=50, verbose_name='nom élève')),
                ('contact', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('time_availability', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('REVIEWING', 'Validation en cours'), ('ACCEPTED', 'Accepté')], default='REVIEWING', max_length=9, verbose_name='état')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='commentaire administrateur')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='papseur')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paps_time', models.DateTimeField(auto_now_add=True, verbose_name='moment du paps')),
                ('state', models.CharField(choices=[('REVIEWING', 'Validation en cours'), ('REJECTED', 'Refusé'), ('ACCEPTED', 'Accepté')], default='REVIEWING', max_length=9, verbose_name='état')),
                ('tutoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tutorings.Tutoring', verbose_name='paps')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='papseur')),
            ],
            options={
                'unique_together': {('tutoring', 'user')},
            },
        ),
    ]
