# Generated by Django 2.1.5 on 2019-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
    ]
