# Generated by Django 2.1.5 on 2019-01-30 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0003_page_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('rank', models.IntegerField(default=0, help_text="Ordre d'apparition dans la liste des membres de l'asso (ordre alphabétique pour les valeurs égales)")),
                ('static_page', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('marketplace', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('vote', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='associations.Association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'association')},
        ),
    ]
