# Generated by Django 2.0.7 on 2018-08-04 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_auto_20180803_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='groups',
            field=models.ManyToManyField(blank=True, to='associations.Group'),
        ),
        migrations.AlterField(
            model_name='association',
            name='library',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='associations.Library'),
        ),
        migrations.AlterField(
            model_name='association',
            name='market',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='associations.Marketplace'),
        ),
        migrations.AlterField(
            model_name='association',
            name='publication',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='associations.Publication'),
        ),
        migrations.AlterField(
            model_name='election',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 0, 18, 16, 626047)),
        ),
    ]
