# Generated by Django 2.1.5 on 2019-01-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0004_auto_20190130_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['rank']},
        ),
    ]
