# Generated by Django 2.1.7 on 2019-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0005_auto_20190131_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='association',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
