# Generated by Django 2.1.7 on 2019-02-19 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0006_auto_20190219_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loanable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('comment', models.TextField(null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanables', to='associations.Library')),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='library',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='object',
        ),
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Emprunté'), ('CANCELLED', 'Annulé'), ('RETURNED', 'Rendu')], max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.AddField(
            model_name='loan',
            name='loanable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='associations.Loanable'),
        ),
    ]
