version: "3"
services:
  # chat:
    # restart: always
    # build:
    #   context: ./chat_server/ 
    #   dockerfile: chat_server.Dockerfile
    # links:
    #   - db:db
    # env_file:
    #    - ./chat_server/db.env
    # ports:
    #   - 3000:3000

  db:
    build:
      context: docker
      dockerfile: db.Dockerfile
    volumes:
      - ./volumes:/var/lib/postgresql/data/
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    profiles: ["dev", "prod"]
  
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    links:
      - db:db
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    volumes:
    - "./backend:/app/backend"
    profiles: ["dev", "prod"]
    networks:
      - default
      - sso_sso

  frontend-dev:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles: ["dev"]

  frontend-prod:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    profiles: ["prod"]

networks:
  sso_sso:
    external: true