# Generated by Django 2.1.7 on 2019-02-27 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageforum',
            name='down_vote',
            field=models.ManyToManyField(related_name='_messageforum_down_vote_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageforum',
            name='up_vote',
            field=models.ManyToManyField(related_name='_messageforum_up_vote_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
