# Generated by Django 2.1.1 on 2019-01-15 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='texte du choix')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='question')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('state', models.CharField(choices=[('REVIEWING', 'Validation en cours'), ('REJECTED', 'Refusé'), ('ACCEPTED', 'Accepté')], default='REVIEWING', max_length=9, verbose_name='état')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='date de publication')),
                ('admin_comment', models.TextField(blank=True, verbose_name='commentaire administrateur')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Poll', verbose_name='sondage'),
        ),
    ]
