# Generated by Django 2.1.5 on 2019-01-29 10:55

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='poll', chained_model_field='poll', on_delete=django.db.models.deletion.CASCADE, sort=False, to='polls.Choice', verbose_name='choix'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'user')},
        ),
    ]
