# Generated by Django 2.2.5 on 2019-10-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("associations", "0001_initial"), ("forum", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "scoped_to_model",
                    models.CharField(
                        choices=[
                            ("association", "association"),
                            ("forum_theme", "forum_theme"),
                            ("global", "global"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "scoped_to_pk",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={"unique_together": {("name", "scoped_to_model", "scoped_to_pk")}},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "association",
                    models.ManyToManyField(
                        related_name="tags", to="associations.Association"
                    ),
                ),
                (
                    "loanable",
                    models.ManyToManyField(
                        related_name="tags", to="associations.Loanable"
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        related_name="tags", to="associations.Media"
                    ),
                ),
                (
                    "message_forum",
                    models.ManyToManyField(
                        related_name="tags", to="forum.MessageForum"
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tags.Namespace",
                    ),
                ),
                (
                    "page",
                    models.ManyToManyField(related_name="tags", to="associations.Page"),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="tags", to="associations.Product"
                    ),
                ),
                (
                    "role",
                    models.ManyToManyField(related_name="tags", to="associations.Role"),
                ),
                (
                    "theme",
                    models.ManyToManyField(related_name="tags", to="forum.Theme"),
                ),
                (
                    "topic",
                    models.ManyToManyField(related_name="tags", to="forum.Topic"),
                ),
            ],
            options={"unique_together": {("value", "namespace")}},
        ),
    ]
