# Generated by Django 2.2.3 on 2019-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('choice', models.ManyToManyField(related_name='tag', to='associations.Choice')),
                ('event', models.ManyToManyField(related_name='tag', to='associations.Event')),
                ('file', models.ManyToManyField(related_name='tag', to='associations.File')),
                ('folder', models.ManyToManyField(related_name='tag', to='associations.Folder')),
                ('loan', models.ManyToManyField(related_name='tag', to='associations.Loan')),
                ('loanable', models.ManyToManyField(related_name='tag', to='associations.Loanable')),
                ('message_forum', models.ManyToManyField(related_name='tag', to='forum.MessageForum')),
                ('page', models.ManyToManyField(related_name='tag', to='associations.Page')),
                ('product', models.ManyToManyField(related_name='tag', to='associations.Product')),
                ('role', models.ManyToManyField(related_name='tag', to='associations.Role')),
                ('theme', models.ManyToManyField(related_name='tag', to='forum.Theme')),
                ('topic', models.ManyToManyField(related_name='tag', to='forum.Topic')),
            ],
        ),
    ]
