# Generated by Django 2.0.5 on 2018-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pseudo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='User pseudo')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=50, verbose_name='User first name')),
                ('lastname', models.CharField(max_length=50, verbose_name='User last name')),
                ('email', models.EmailField(max_length=160, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
