# Generated by Django 2.0.6 on 2018-07-22 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, help_text='adresse en dehors de la Meuh', max_length=512),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='student',
            name='city_of_origin',
            field=models.CharField(blank=True, help_text="ville d'origine", max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_ast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_in_gapyear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_isupfere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='minesparent',
            field=models.ManyToManyField(blank=True, related_name='fillots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='option',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, max_length=128, verbose_name='numéro de chambre'),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate',
            field=models.ManyToManyField(blank=True, related_name='_student_roommate_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='sports',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
