# Generated by Django 2.1.1 on 2019-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_1A',
            field=models.BooleanField(default=True),
        ),
    ]
