# Generated by Django 2.1.5 on 2019-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_1a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-promo', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='user',
            name='promo',
            field=models.IntegerField(default=18, verbose_name='Promotion'),
        ),
    ]
