# Generated by Django 2.1.7 on 2019-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190131_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promo',
            field=models.IntegerField(verbose_name='Promotion'),
        ),
    ]
