# Generated by Django 2.2.10 on 2020-04-19 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('required', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.PositiveSmallIntegerField(choices=[(1, 'VERY_UNSATISFIED'), (2, 'UNSATISFIED'), (3, 'NEUTRAL'), (4, 'SATISFIED'), (5, 'VERY_SATISFIED')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(blank=True, max_length=128)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Rating')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ReviewForm'),
        ),
        migrations.CreateModel(
            name='HasVoted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='courses/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('iploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ReviewForm'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('review_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ReviewForm')),
            ],
        ),
    ]
