# Generated by Django 2.2.10 on 2020-04-20 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('have_voted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('S', 'SCALE'), ('C', 'COMMENT')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.SmallIntegerField(choices=[(1, 'VERY_UNSATISFIED'), (2, 'UNSATISFIED'), (3, 'NEUTRAL'), (4, 'SATISFIED'), (5, 'VERY_SATISFIED')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='courses.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='courses.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='courses.ReviewForm'),
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='courses/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursemedia', to='courses.Course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursemedia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='review_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.ReviewForm'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.Question')),
            ],
        ),
    ]
