# Generated by Django 2.2.10 on 2020-04-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200421_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewForm',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='review_form',
            new_name='form',
        ),
    ]
