# Generated by Django 2.2.10 on 2020-04-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200429_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('form', 'label')},
        ),
    ]
