# Generated by Django 2.2.10 on 2020-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200421_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('S', 'SCALE'), ('C', 'COMMENT')], default='COMMENT', max_length=1),
        ),
    ]
