# Generated by Django 2.1.5 on 2019-01-28 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('associations', '0003_page_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(verbose_name='Souscris')),
                ('association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='associations.Association', verbose_name='Association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilisteur')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nom du widget')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed', models.BooleanField(verbose_name='Affiché')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Widget', verbose_name='Widget')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='widgetsubscription',
            unique_together={('user', 'widget')},
        ),
        migrations.AlterUniqueTogether(
            name='associationsubscription',
            unique_together={('user', 'association')},
        ),
    ]
