# Generated by Django 2.1.7 on 2019-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('promotion', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
