# Generated by Django 2.2.4 on 2019-08-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('promotion', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('equirepartition', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voeux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voeux', models.TextField()),
                ('isNew', models.BooleanField(default=True)),
                ('outcome', models.IntegerField(default=-1)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repartitions.Repartition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('num', models.IntegerField()),
                ('min_eleves', models.IntegerField()),
                ('max_eleves', models.IntegerField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repartitions.Repartition')),
            ],
        ),
    ]
