name: Blackend

on:
  pull_request:
      branches: [ master ]

jobs:
  blackend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install black
      - run: black --check backend
