name: Prettier

on:
  pull_request:
      branches: [ master ]

jobs:
  prettier:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Run Prettier
        run: prettier frontend/**/*.ts*
