from __future__ import unicode_literals

from datetime import timedelta

from django.conf import settings

from authentication.keys.public import PUBLIC_KEY

# TODO: use the DRF settings object.
API_SETTINGS = {
    # Algorithm.
    # The keys can be generated by following the instructions at
    # https://rietta.com/blog/openssl-generating-rsa-key-from-command/.
    "ALGORITHM": "RS256",
    "PUBLIC_KEY": PUBLIC_KEY,
    # GET parameter for the token.
    "GET_PARAMETER": "access",
    # Cookie.
    "ACCESS_TOKEN_COOKIE_NAME": "jwt_access_token",
    # Life time.
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    # Claims.
    "AUDIENCE": "portail",
    "ISSUER": "sso_server",  # The allowed issuer.
    "USER_ID_CLAIM_NAME": "user",
}

PROD_MODE = not settings.DEBUG
